name: Pipeline

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build_on_ubuntu_22_04:
    name: Build on Ubuntu 22.04
    uses: ./.github/workflows/build.yaml
    with:
      ubuntu-version: 22.04

  build_on_ubuntu_latest:
    name: Build on Ubuntu latest
    uses: ./.github/workflows/build.yaml
